version: "0.2"
dictionaries:
  - project-words
  - english
  - ethereum
  - bash
  - linux
dictionaryDefinitions:
  - name: project-words
    path: ./project-words.txt
    addWords: true
ignorePaths:
  - "cspell.config.yaml"
  - "pnpm-*.yaml"
  - "**/.gitignore"
  - "out/**"
  - "lib/**"
  - "dependencies/**"
  - "cache/**"
