[31337]
endpoint_url = "http://127.0.0.1:8545"

[42161]
endpoint_url = "${ARBITRUM_ONE_RPC_URL}"

[42161.address]
IDOSToken = "0x68731d6F14B827bBCfFbEBb62b19Daa18de1d79c"
IDOSNodeStaking = "0x6132F2EE66deC6bdf416BDA9588D663EaCeec337"

[421614]
endpoint_url = "${ARBITRUM_SEPOLIA_RPC_URL}"

[421614.address]
IDOSToken = "0xdb3b7BB52dD6cfE1157022bde6dfc28D8101e180"
IDOSNodeStaking = "0xA07742fd930A8dF8dF35eE483aEe933545f84378"
