[profile.default]
solc = "0.8.28"
optimizer = true
optimizer_runs = 200
show_progress = true
fs_permissions = [
    { access = "read-write", path = "./deployments.toml" }
]
libs = ["dependencies"]

[rpc_endpoints]
arbitrum_one = "${ARBITRUM_ONE_RPC_URL}"
arbitrum_one_sepolia = "${ARBITRUM_SEPOLIA_RPC_URL}"

[dependencies]
"@openzeppelin-contracts" = "5.5.0"
